### PR TITLE
Remove `#[cfg(not(test))]` feature gate on `xflags!`

### LINKED ISSUE #14: rust-analyzer fails to resolve invocations of `xflags::xflags!`
`xflags` is for the most part great (easy arg parsing without the compile time hit <3), but there are a few annoyances with using it. One of them is that rust-analyzer seems to be upset by it, producing errors like

```
unresolved macro `xflags::xflags!` rust-analyzer(unresolved-macro-call)
```

when the file containing the invocation happens to be open.

This, for the most part, isn't that big of a deal (just close the file, r-a shuts up, and everything works fine), but is an annoyance, and I've had to explain that this is what you should do to others on projects using xflags a couple times, so I figured I'd file a bug about it.

I assume the *real* solution is for rust-analyzer to get smarter, but... perhaps there's some workaround that xflags could to at least make this less annoying?

### PR DESCRIPTION
**Pull request by lnicola**
Closes #14

### CODE REVIEW

**Comment by jplatte** [comment]
Ping @matklad

**Comment by matklad** [comment]
bors r+

Slow response is partially explained by me fleeing from Russia.

Let me also invite @lnicola as a co-owner of the crate/repo, just in case.

**Comment by jplatte** [comment]
> Slow response is partially explained by me fleeing from Russia.

Oh 😞 Wish you all the best! ♥️

**Comment by lnicola** [comment]
Can we also invite @Veykril?

**Comment by matklad** [comment]
Done!

**Pull request merged**
